service:
  name: ignite-node-chapter-06-desafio-01

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  
provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  createTodo:
    handler: src/functions/createTodo.handle
    events:
      - http:
          path: /createTodo/{userid}
          method: POST
          cors: true
  getTodos:
    handler: src/functions/getTodos.handle
    events:
      - http:
          path: /getTodos/{userid}
          method: GET
          cors: true

resources:
  Resources:
    dbTodos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
